apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
type: Opaque
data:
  DB_USER: {{ default "" .Values.secrets.DB_USER | b64enc | quote }}
  DB_PASS: {{ default "" .Values.secrets.DB_PASS | b64enc | quote }}
  DB_HOST: {{ default "" .Values.secrets.DB_HOST | b64enc | quote }}
  DB_NAME: {{ default "" .Values.secrets.DB_NAME | b64enc | quote }}
